export default {
	Index:{
		path:'../Component/index/index'
	},
	AcademicYear:{
		path:'../Component/academicyear/academicyear'
	},
	TermDetail:{
		path:'../Component/academicyear/termdetail'
	},
	//上课时间
	SchoolTime:{
		path:'../Component/schooltime/schooltime'
	},
	TimeSetting:{
		path:'../Component/schooltime/timesetting'
	},
	//课程类别
	CourseCategory:{
		path:'../Component/coursecategory/CourseCategory'
	},
	//教学模式
	Teach:{
		path:'../Component/teach/teach'
	},
	SelectCourse:{
		path:'../Component/coursesetting/selectcourse'
	},
	//选课任务设置第1、2步
	SelectCourseAddTask:{
		path:'../Component/coursesetting/selectcourseaddtask'
	},
	CoursePreferenceSet:{
		path:'../Component/coursesetting/coursepreferenceset'
	},
	AddCourse:{
		path:"../Component/coursesetting/addcourse/addcourse"
	},
	CourseSetting:{
		path:"../Component/coursesetting/coursesetting"
	},
	AddCourseTask:{
		path:"../Component/coursesetting/addcoursetask"
	},
	StuSelectCourse:{
		path:"../Component/studentcoursesetting/stuselectcourse"
	},
	//教室列表
	Classroom:{
		path:"../Component/classroom/classroom"
	},
	ClassroomList:{
		path:"../Component/classroom/classroomlist"
	},

	//学生管理
	Students:{
		path:"../Component/students/students"
	},
	StudentAccountNull:{
		path:"../Component/students/studentaccountnull"
	},
	ResetPasswordSuccess:{
		path:"../Component/students/resetpasswordsuccess"
	},
	//教师管理 
	Teachers:{
		path:"../Component/teachers/teachers"
	},
	TeacherAccountNull:{
		path:"../Component/teachers/teacheraccountnull"
	},
	TeacherInformation:{
		path:"../Component/teachers/teacherinformation"
	},
	TeacherEdit:{
		path:"../Component/teachers/teacheredit"
	},

	//选课管理 学生选课管理
	StudentCourse:{
		path:"../Component/studentcourse/studentcourse"
	},
	NameList:{
		path:"../Component/studentcourse/namelist"
	},

	//成绩管理
	Achievement:{
		path:'../Component/achievement/achievement'
	} 
}
